### ISSUE TITLE
IE 11 issue

### ISSUE THREAD

**Issue by ziveo** [jsillitoe/react-currency-input#10]
When using component in IE 11 app can't be loaded.

I am getting following error message:

<img width="465" alt="screen shot 2017-02-10 at 4 12 07 pm" src="https://cloud.githubusercontent.com/assets/855512/22844342/c8cc11a8-efab-11e6-8977-6be2b1867019.png">

**Comment by jsillitoe** [comment]
Thank you for the report.  It makes use of the [Object.assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) function to pass on properties to the actual input element.  Support is not universal, but I am a bit reluctant to add a polyfill since individual projects may want to implement their polyfills in different ways.    

There are a few node modules out there that would fix the problem for you, for example [https://www.npmjs.com/package/es6-object-assign](https://www.npmjs.com/package/es6-object-assign)

**Comment by jsillitoe** [comment]
After more though, i decided to get rid of the Object.assign and use a more generic way to clone the props.  This issue should be fixed for versions 1.2.2 and up.  No need for other modules or libraries.

**Comment by ziveo** [comment]
Excellent job Joe.
Thank you for your effort in fixing this issue.
