### ISSUE TITLE
Value is restarting after the fourth digit

### ISSUE THREAD

**Issue by wellyal** [jsillitoe/react-currency-input#38]
This behavior is happening:

![jul-03-2017 14-23-25](https://user-images.githubusercontent.com/3047016/27802612-40572d42-5ffb-11e7-8347-4f5d66d72b19.gif)

```javascript
<Currency
  ref={currency => { this.currency = currency }}
  className={currencyClass}
  precision={2}
  decimalSeparator=","
  value={this.state.value}
  thousandSeparator="."
  prefix="R$ "
  onChange={this.handleValue}
/>
```
Troubleshooting helper -> console log from react-currency-input/lib/index.js:231
version -> 1.2.6
Google Chrome -> Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by wellyal** [comment]
UPDATE: I have updated my currency lib to the final realease (1.3.2), still having the same issue. When reachs the fouth digit the whole number is being selected causing it to erase all the value when I press the next number.

**Comment by bdox** [comment]
Yeah,  this is definitely happening. I updated from 1.2.6 and found this during regression. I also noticed that there was a breaking change for initialValue that I will fix in a PR. 

I haven't been able to find exactly what changed, due to the strange branching/release strategy used in this repo, but the code that is doing the selection is in the componentDidUpdate event.

**Comment by bdox** [comment]
I found this fork which has updated the selection code, hoping he will PR that back in.

https://github.com/tncalvert/react-currency-input/tree/selection_changes

**Comment by tcg** [comment]
Came here to possibly report this, but I see you all beat me to it. I'm not new to web dev, but newish to modern JS/React, so not able to provide a PR/fix. Thanks @bdox for the suggested fork/branch. I will try that out in the mean time.
