### ISSUE TITLE
Non-standard conversion from given value into displayed value

### ISSUE THREAD

**Issue by igorsantos07** [jsillitoe/react-currency-input#9]
If a string (or a number, when it works (#6)) is given as `value` with not enough decimals when a said precision is needed, some integers are turned into decimals.

Example: `<CurrencyInput value="6300" precision="2"/>` yields a field like `[63.00]` instead of `[6300.00]`.

An easy way to avoid that when receiving numbers is as follows, but string values would require manual work:
```js
    if (typeof value == 'number') {
      value = Number(value).toLocaleString(undefined, {
            style                : 'decimal',
            minimumFractionDigits: precision,
            maximumFractionDigits: precision
      })
    }
```

**Comment by jsillitoe** [comment]
This issue should now be fixed in the latest release (also published to npmjs.com).  Thank you for this bug report and the sample code!

I decided it would be appropriate to coerce string values (using parseFloat) into numbers then passing them through the toLocaleString function.  A number of unit tests were added for this, including the example you presented, so thank you again.
